# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af767e31280c550066ae5a18490b1245aa570442ff1ba1a016cc903cd94eb76cde2b32184977610b2dab3014b04d26370503e3cb1feba1067282737aed63f0cf

test:
  secret_key_base: 938d1eb4c2b1ddbe8aaf17b203c5b18b3fde9b1e58821307df9daf66d720ffa2c29180913e27a3e04bf22c8b6c4e25678918345c230d88d96a2794541ecbbd75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
